### ISSUE TITLE
link to speakers page points to temporary announcment page 

### ISSUE THREAD

**Issue by david-barnett** [bytemal/bytemal-2024#1]
Just noticed this when i visited the website
https://github.com/bytemal/bytemal-2024/blob/667ff4bcb3d13f762a11be3beff96f7d2728cdc4/_layouts/default.html#L44

Looking forward to the event, good luck with the remaining organisation 2024 team! :)

**Comment by jarnokoetsier** [comment]
Yes, that's right. This was done on purpose since the speakers were not yet known. Now the speakers are known, I changed the link to the correct speaker page. Thanks for letting me know!
